-- =============================================
-- 02_DML/04_news.sql
-- Seed: dbo.news (30 bài viết gỗ óc chó)
-- =============================================
-- Idempotent: upsert theo news_id.
-- Nội dung 30 bài lấy từ script `database_news.sql` cũ (đã rà soát).
SET NOCOUNT ON;

-- Xóa dữ liệu seed cũ (GEN-*, WALNUT-*, news-001, news-002) để tránh trùng lặp
DELETE FROM dbo.news
WHERE news_id LIKE N'GEN-%'
   OR news_id LIKE N'WALNUT-%'
   OR news_id IN (N'news-001', N'news-002');

INSERT INTO dbo.news (news_id, title, summary, content, news_image, news_category_id, tags, view_count, hidden, del_flag, created_user, created_date, updated_user, updated_date)
SELECT article.news_id, article.title, article.summary, article.content, article.news_image, category.id, article.tags,
       article.view_count, 0, 0, N'content-seed', article.publish_date, N'content-seed', article.publish_date
FROM (VALUES
    (N'WALNUT-2026-001', N'Xu hướng nội thất gỗ óc chó 2026: Ấm áp, tinh giản và bền vững', N'Không gian năm 2026 ưu tiên đường nét gọn, bảng màu ấm và các chi tiết gỗ óc chó được sử dụng có chủ đích.', N'Gỗ óc chó tiếp tục được ưa chuộng nhờ sắc nâu trầm, hệ vân tự nhiên và khả năng kết hợp với nhiều vật liệu. Thay vì phủ kín không gian, xu hướng mới dùng gỗ tại các điểm nhấn như vách tivi, bàn ăn và hệ tủ may đo để giữ sự thoáng đãng. Thiết kế bền vững cũng chú trọng kết cấu dễ bảo trì và hoàn thiện bề mặt an toàn cho gia đình.', N'/media/gallery/walnut-villa-living.webp', N'go-oc-cho', N'gỗ-óc-chó,xu-hướng-2026,nội-thất', 428, '2026-07-22T09:00:00'),
    (N'WALNUT-2026-002', N'Cách nhận biết gỗ óc chó Bắc Mỹ đạt chuẩn', N'Những dấu hiệu quan trọng giúp phân biệt gỗ óc chó đúng chủng loại trước khi đặt đóng nội thất.', N'Gỗ óc chó Bắc Mỹ thường có phần dát gỗ sáng, tâm gỗ nâu socola và đường vân chuyển động mềm mại. Khi kiểm tra vật liệu, cần quan sát cả mặt cắt, độ đồng đều sau sấy và hồ sơ nguồn gốc thay vì chỉ nhìn màu sơn bề mặt. Một mẫu gỗ đạt chuẩn phải ổn định độ ẩm và không có dấu hiệu cong vênh hoặc nứt đầu thanh.', N'/media/gallery/walnut-joinery-detail.webp', N'chia-se-chuyen-mon', N'gỗ-óc-chó,vật-liệu,kinh-nghiệm', 176, '2026-07-10T10:30:00'),
    (N'WALNUT-2026-003', N'Hoàn thiện biệt thự Ecopark với nội thất gỗ óc chó đồng bộ', N'Công trình sử dụng gỗ óc chó xuyên suốt phòng khách, phòng ăn và phòng ngủ nhưng vẫn giữ được sự nhẹ nhàng.', N'Đội ngũ thiết kế lựa chọn cùng một tông màu hoàn thiện cho các khu vực chính để tạo mạch không gian thống nhất. Mỗi phòng được điều chỉnh tỷ lệ gỗ, đá và vải khác nhau nhằm tránh cảm giác nặng nề. Hệ tủ và vách trang trí được sản xuất theo kích thước thực tế, giúp các chi tiết tiếp giáp gọn và thuận tiện sử dụng.', N'/media/gallery/quiet-lounge.jpg', N'hoan-thien-cong-trinh', N'biệt-thự,ecopark,gỗ-óc-chó', 254, '2026-06-25T08:15:00'),
    (N'WALNUT-2026-004', N'Phối gỗ óc chó với đá tự nhiên trong phòng bếp', N'Cách cân bằng sắc nâu của gỗ với bề mặt đá để căn bếp sang trọng mà không tối.', N'Đá sáng màu có vân nhẹ giúp làm nổi bật sắc nâu của cánh tủ gỗ óc chó và tăng độ thoáng cho khu bếp. Với đảo bếp lớn, có thể dùng đá tối hơn ở mặt bàn nhưng cần bổ sung ánh sáng hắt dưới tủ. Các vị trí gần chậu rửa nên ưu tiên veneer hoặc gỗ đã xử lý kỹ, đồng thời thiết kế khe thoáng để hạn chế tích tụ độ ẩm.', N'/media/gallery/walnut-villa-kitchen.webp', N'chia-se-chuyen-mon', N'phòng-bếp,đá-tự-nhiên,phối-màu', 91, '2026-06-08T14:00:00'),
    (N'WALNUT-2026-005', N'Bộ sưu tập bàn ăn gỗ óc chó cạnh cong tự nhiên', N'Các mẫu bàn ăn mới khai thác đường cong mềm và vẻ đẹp nguyên bản của hệ vân gỗ óc chó.', N'Bộ sưu tập tập trung vào mặt bàn bo cong, chân bàn thanh thoát và tỷ lệ phù hợp với căn hộ hiện đại. Bề mặt được hoàn thiện mờ để giữ cảm giác tự nhiên khi chạm và hạn chế lộ vết xước nhỏ. Khách hàng có thể lựa chọn kích thước từ sáu đến mười ghế cùng nhiều phương án ghế bọc da hoặc vải.', N'/media/gallery/arched-dining.jpg', N'go-oc-cho', N'bàn-ăn,bộ-sưu-tập,gỗ-óc-chó', 215, '2026-05-21T09:45:00'),
    (N'WALNUT-2026-006', N'Bàn giao căn hộ Westlake với hệ tủ óc chó may đo', N'Hệ tủ óc chó may đo tổ chức lưu trữ, làm việc và trưng bày trên một mặt đứng liền mạch, mang lại sự ấm áp có chủ đích cho căn hộ Westlake.', N'<div class="news-project-facts"><div><span>Loại hình</span><strong>Căn hộ</strong></div><div><span>Khu vực</span><strong>Westlake</strong></div><div><span>Hạng mục</span><strong>Hệ tủ óc chó may đo</strong></div><div><span>Tích hợp</span><strong>Lưu trữ · Làm việc · Trưng bày</strong></div></div><p>Trong căn hộ Westlake, sự sang trọng không đến từ việc phô bày quá nhiều chi tiết. Trọng tâm của công trình là hệ tủ gỗ óc chó được thiết kế theo hiện trạng, tạo nên một mặt đứng ấm, gọn và có nhịp điệu. Mỗi công năng được sắp xếp để phục vụ đời sống hằng ngày nhưng vẫn giữ cho không gian cảm giác thư thái.</p><h2>Bài toán bắt đầu từ hiện trạng</h2><p>Với nội thất may đo, bản vẽ chỉ thực sự chính xác khi được đặt trên dữ liệu của không gian thật. Trước khi sản xuất, đội ngũ khảo sát kỹ các góc tường và đường kỹ thuật của căn hộ. Những vị trí tiếp giáp, khoảng mở cánh và hướng tiếp cận khi sử dụng cần được nhìn nhận như một hệ thống thay vì những chi tiết rời rạc.</p><p>Cách làm này giúp hạn chế sai số trong quá trình lắp đặt và cho phép hệ tủ ôm sát kiến trúc sẵn có. Khi tỷ lệ, khe tiếp giáp và vị trí sử dụng được xử lý đồng bộ, nội thất có cảm giác như một phần nguyên bản của căn hộ, thay vì một khối đồ được bổ sung về sau.</p><h3>Đo theo kiến trúc, thiết kế theo thói quen</h3><p>Một hệ tủ đẹp chưa đủ; nó cần thuận tiện trong từng thao tác hằng ngày. Khu lưu trữ kín giữ cho mặt đứng yên tĩnh, các khoang mở dành cho sách và vật phẩm tạo điểm dừng thị giác, còn bàn làm việc được đặt trong cùng ngôn ngữ vật liệu để không phá vỡ tổng thể. Sự phân lớp này giúp gia đình chuyển đổi linh hoạt giữa làm việc, đọc sách và nghỉ ngơi.</p><aside class="news-editor-note"><span>Góc nhìn thiết kế</span><p>Luxury trong nội thất may đo nằm ở cảm giác mọi thứ đã ở đúng vị trí: dễ tiếp cận khi cần, kín đáo khi không sử dụng và nhất quán trong từng điểm chạm.</p></aside><h2>Một mặt đứng, ba lớp công năng</h2><p>Thay vì chia nhỏ căn phòng bằng nhiều món đồ rời, hệ tủ hợp nhất lưu trữ, làm việc và trưng bày trong cùng một cấu trúc. Giải pháp này vừa tận dụng diện tích, vừa giảm nhiễu thị giác và tạo sự liên tục cho không gian.</p><div class="news-design-principles"><div><span>01</span><h3>Lưu trữ kín</h3><p>Những vật dụng sử dụng theo thời điểm được đưa về các khoang đóng để giữ bề mặt thị giác gọn gàng.</p></div><div><span>02</span><h3>Làm việc tập trung</h3><p>Bàn làm việc trở thành một phần của hệ tủ, tạo cảm giác liền mạch thay vì xuất hiện như một món đồ độc lập.</p></div><div><span>03</span><h3>Trưng bày có chọn lọc</h3><p>Khoang mở tạo nhịp sáng tối và dành không gian cho những vật phẩm có giá trị tinh thần với gia chủ.</p></div></div><div class="news-media-gallery"><
